### ISSUE TITLE
How can I move through folder?

### ISSUE THREAD

**Issue by mpagels** [juftin/browsr#1]
I can not move through the folder/file tree on the left side. Is this intended, or did I misunderstand the purpose of the app?

Like in this image, I can not move the yellow bar with the arrow keys.
![example](https://camo.githubusercontent.com/64a7bdec59a473c3570772e2191ff27cb2730e0f9f045329517a23b81dcca302/68747470733a2f2f692e696d6775722e636f6d2f3661706b4932512e706e67)

**Comment by juftin** [comment]
You can click on the directory tree to navigate it. Once you click on it you can use your arrow keys too.

**Comment by mpagels** [comment]
Ah okay. Thanks for taking the time to prepare a screen recording. Really appreciate it. For me, it is not working. But maybe because I use `Fluent Terminal` to access my WSL on Windows? Do you know something about it?

**Comment by juftin** [comment]
Oh bummer. I'm not exactly sure. The app is built with [Textual](https://textual.textualize.io/) - I searched through their issues for WSL / Fluent issues but haven't seen anything. I'd be interested to know if you have the same issue with the `Windows Terminal`

**Comment by mpagels** [comment]
I just read this in the `textual` [docs](textualize.io/getting_started/#linux-all-distros)

>All Linux distros come with a terminal emulator that can run Textual apps.

So I tried the `ubuntu` terminal, that comes with the installation on windows and here it works very well. So it seems, that it is indeed a `Fluent Terminal` issue.

**Comment by mpagels** [comment]
Ok, I found it! Haha, super stupid from my side. I have to `tab` into it. I tried the obvious and pushed every button on my keyword and after typing the `tab` key, it worked. The mouse is unfortunately not recognized, even after the `tab` trick. But this is not an issue for me.

I will close the issue. Thanks for the help.
