### ISSUE TITLE
Freezes and shows junk when previewing a binary file

### ISSUE THREAD

**Issue by Slackadays** [juftin/browsr#12]
I'm trying out browsr and I came across a nasty bug: if I preview a file that's just binary data, some of that data makes its way out of the preview window and if it's a lot of data, browsr freezes despite running on a hulking Ryzen 5900X. Here's a video that makes this clearer :)

https://github.com/juftin/browsr/assets/69403549/a95bd003-695f-4b8d-bec2-ab1a873e48be

**Comment by juftin** [comment]
I ended up just raising an error when a file's contents can't be properly encoded. There are just too many problematic characters possible in a binary file that can corrupt a TUI app.
![image](https://github.com/juftin/browsr/assets/49741340/f8c028d9-fb63-4513-a563-6246a009f69d)
