### ISSUE TITLE
Show file on navigation

### ISSUE THREAD

**Issue by jalanb** [juftin/browsr#20]
When navigating in the file tree only <up>/<down> arrows are recognised. 

I'd suggest <left>/<right> should also be recognised

- <left>: go up to parent directory
- <right> go down into children of current directory, either to first item in that dir, or to previous item in that dir (if user was there before)

Also - nodes are highlighted in directory tree when using <up>/<down>, but the file viewer is not updated. When I hit <down arrow> to (e.g.) move to the file `fred.py` in directory tree, then I should also see text of `fred.py` on the right hand side

**Comment by juftin** [comment]
I like the navigating through the directory tree ideas - I'd have to find a way to further customize the [Textual Directory Tree Widget](https://textual.textualize.io/widgets/directory_tree/) to handle something like that. 

For the code block to render a new code file, the Textual app sends a message, [FileSelected](https://textual.textualize.io/widgets/directory_tree/#textual.widgets._directory_tree.DirectoryTree.FileSelected). However there isn't a message sent on hover or when selecting with the arrow keys, that's possible but might be difficult to ratelimit for fast movement of a mouse. Instead you can use the `ENTER` key to "select" the file when hovered over it, would that work for you?

**Comment by jalanb** [comment]
`ENTER` key works fine for me, especially given fast navigation with arrow keys
