### ISSUE TITLE
Provide storage options to fsspec

### ISSUE THREAD

**Issue by ap--** [juftin/browsr#24]
Thanks for this super useful tool! ❤️ 

Is there a way to provide fsspec storage_options, to `browsr`? Specifically I would like to access an s3 bucket with `{"anon": True}` as in:

```python
storage_options = {"anon": True}
UPath("s3://recount-opendata/", **storage_options)
```

Cheers,
Andreas 😃

**Comment by juftin** [comment]
Great idea @ap--, this will get released momentarily:

```shell
browsr s3://recount-opendata -k anon=True
```

**Comment by ap--** [comment]
Thank you for the quick turnaround 😊
