### ISSUE TITLE
tests/test_screenshots.py:30: AssertionError

### ISSUE THREAD

**Issue by carlosal1015** [juftin/browsr#27]
Hi, [this issue](https://aur.archlinux.org/packages/browsr#comment-932336) was reported. I do not know the reason that is passing in text mode (only terminal).

![image](https://github.com/juftin/browsr/assets/21283014/e5498ed6-3b87-4267-abc5-50217dc25b29)

**Comment by juftin** [comment]
Hey @carlosal1015 this looks like a Textual version issue. Is it possible the versions aren't pinned for the underlying dependencies?

Also, what exactly is https://aur.archlinux.org/packages/browsr?

**Comment by carlosal1015** [comment]
Then no worries, thanks for feedback, this link store a git repository, mainly a file called [PKGBUILD](https://wiki.archlinux.org/title/PKGBUILD) that enables to install software with [`makepkg -si`](https://wiki.archlinux.org/title/Makepkg) instruction.
