### ISSUE TITLE
Mark xsh and xonshrc as Python for xonsh shell minimal support

### ISSUE THREAD

**Issue by anki-code** [juftin/browsr#46]
Please mark `*.xsh` and `*.xonshrc` as Python for syntax highlighting of [xonsh shell](https://xon.sh) scripts.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by juftin** [comment]
Textual currently leverages  [pygments](https://github.com/pygments/pygments) (`pygments.gues_lexer`) (`browsr` -> `textual` -> `rich` -> `pygments`) to handle syntax highlighting - the best way to gain this support would be to add the feature [upstream](https://github.com/pygments/pygments/blob/26ffe8f472d18ed190a5ced00335682c618037d4/pygments/lexers/python.py#L25-L58). I _think_ adding a shebang might also handle this.

**Comment by juftin** [comment]
Hopefully soon, I'll be replacing pygments with tree-sitter for syntax highlighting. I'll make sure these extensions are handled then inside of browsr.
